### ISSUE TITLE
Support for variable length sequences and bi-directional GRU

### ISSUE THREAD

**Issue by elixir-code** [Maghoumi/JitGRU#3]
I am working with a NLP model which uses **bi-directional GRUs** and also uses a **higher-order derivative** in the loss function.

Is it possible to extend this work to support variable length sequences and also support the bi-directional variant of the GRU?

I am interested in understanding if this technically possible and if implementing it using JIT would give speed improvements over the approach of disabling CUDNN with `with torch.backends.cudnn.flags(enabled=False):` for `nn.GRU`.

P.S.: I understand that Torchscript does not support `PackedSequence` making things difficult.

**Comment by Maghoumi** [comment]
Hi @elixir-code,

In my experience, using Torchscript is almost always faster than disabling CUDNN. 

Adding support for bi-directional GRUs should be possible. Supporting sequences of different lengths however may be a different story. I can think of two approaches, though there may be other better approaches too:

The most straightforward way is using a `for` loop which goes over every sample in the batch. In my experience, this is typically slow. Another possibility is to have all the sequences in the batch padded to some maximum length (similar to how one would create a `PackedSequence`), run the GRU on the batch, then use masking to cut the padding portions. 

I've personally used the latter approach for a related problem in the past. The performance was not amazing, but it was definitely better than the first approach.

Hope this helps!

**Comment by elixir-code** [comment]
Hi @Maghoumi ,

Thank you for your insights. 

I happened to extend the code in this repository along the lines of the latter approach in the above comment to a implement a bi-directional GRU in JIT (TorchScript) with support for variable length sequences. The extended Bi-GRU code can be found at https://gist.github.com/elixir-code/76532057b13299159b572ca649476f1b#file-jit_bigru-py-L93-L189.

P.S.: However, it has a slightly different interface. The Bi-GRU does not return the output corresponding to the hidden states at the last (or T<sup>th</sup>) time step of each the sequences. Also, it requires an input representing the length of each of the sequences. The code is yet to be fully tested.

**Comment by Maghoumi** [comment]
@elixir-code Thanks for sharing.

Once tested, I'd gladly review and merge if you'd like to open a PR.
